# Generated by Django 4.2.6 on 2025-01-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFlockFrost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
